In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("C://Users//bhanu//Downloads//Coursera.csv")
dup = data
data.tail(5)
ude = pd.read_csv("C://Users//bhanu//Downloads//Book1-_1_.csv")

In [3]:
data.shape

(3522, 7)

In [4]:
ude.shape

(14, 8)

In [5]:
data.dtypes

Course Name           object
University            object
Difficulty Level      object
Course Rating         object
Course URL            object
Course Description    object
Skills                object
dtype: object

In [6]:
# data['Course Rating'] = pd.to_numeric(data['Course Rating'], errors='coerce')
# data.info()

In [7]:
platform = ["Coursera" for i in range(3522)]
dup['Platform'] = platform
dup

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,Platform
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...,Coursera
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...,Coursera
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...,Coursera
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...,Coursera
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...,Coursera
...,...,...,...,...,...,...,...,...
3517,"Capstone: Retrieving, Processing, and Visualiz...",University of Michigan,Beginner,4.6,https://www.coursera.org/learn/python-data-vis...,"In the capstone, students will build a series ...",Databases syntax analysis web Data Visuali...,Coursera
3518,Patrick Henry: Forgotten Founder,University of Virginia,Intermediate,4.9,https://www.coursera.org/learn/henry,"�Give me liberty, or give me death:� Rememberi...",retirement Causality career history of the ...,Coursera
3519,Business intelligence and data analytics: Gene...,Macquarie University,Advanced,4.6,https://www.coursera.org/learn/business-intell...,�Megatrends� heavily influence today�s organis...,analytics tableau software Business Intellig...,Coursera
3520,Rigid Body Dynamics,Korea Advanced Institute of Science and Techno...,Beginner,4.6,https://www.coursera.org/learn/rigid-body-dyna...,"This course teaches dynamics, one of the basic...",Angular Mechanical Design fluid mechanics F...,Coursera
3521,Architecting with Google Kubernetes Engine: Pr...,Google Cloud,Intermediate,4.7,https://www.coursera.org/learn/deploying-secur...,"In this course, ""Architecting with Google Kube...",bigtable bigquery SQL Google Cloud Platform...,Coursera

In [8]:
dup = pd.concat([dup,ude], axis=0)
dup

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,Platform
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...,Coursera
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...,Coursera
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...,Coursera
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...,Coursera
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...,Coursera
...,...,...,...,...,...,...,...,...
9,The Data Science Course 2022: Complete Data Sc...,365 Careers,Beginner,4.6,https://www.udemy.com/course/the-data-science-...,"Complete Data Science Training: Mathematics, S...",Fill up your resume with in demand data scienc...,UDEMY
10,Java Programming Masterclass covering Java 11 ...,Tim Buchalka,Beginner,4.5,https://www.udemy.com/course/java-the-complete...,Learn Java In This Course And Become a Compute...,Obtain proficiency in Java 8 and Java 11.,UDEMY
11,Java Programming for Complete Beginners,in28Minutes Official,Beginner,4.54,https://www.udemy.com/course/java-programming-...,Java Programming for Beginners to Java Object ...,CLEAR YOUR JAVA INTERVIEWS: GET ALL the SKILLS...,UDEMY
12,The Complete Java Development Bootcamp,Rayan Slim,Beginner,4.7,https://www.udemy.com/course/the-complete-java...,Become an Experienced Java Developer with Just...,Acquire the Java skills needed to pursue Web D...,UDEMY
13,The Complete Java Certification Course,Imtiaz Ahmad,Beginner,4.5,https://www.udemy.com/course/master-practical-...,Become a confident industry ready core Java de...,Gain enough experience to pass a core Java Pro...,UDEMY

In [9]:
data = dup

In [10]:
data.info()
data

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3536 entries, 0 to 13
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Course Name         3536 non-null   object
 1   University          3536 non-null   object
 2   Difficulty Level    3536 non-null   object
 3   Course Rating       3536 non-null   object
 4   Course URL          3536 non-null   object
 5   Course Description  3536 non-null   object
 6   Skills              3536 non-null   object
 7   Platform            3536 non-null   object
dtypes: object(8)
memory usage: 248.6+ KB

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,Platform
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...,Coursera
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...,Coursera
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...,Coursera
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...,Coursera
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...,Coursera
...,...,...,...,...,...,...,...,...
9,The Data Science Course 2022: Complete Data Sc...,365 Careers,Beginner,4.6,https://www.udemy.com/course/the-data-science-...,"Complete Data Science Training: Mathematics, S...",Fill up your resume with in demand data scienc...,UDEMY
10,Java Programming Masterclass covering Java 11 ...,Tim Buchalka,Beginner,4.5,https://www.udemy.com/course/java-the-complete...,Learn Java In This Course And Become a Compute...,Obtain proficiency in Java 8 and Java 11.,UDEMY
11,Java Programming for Complete Beginners,in28Minutes Official,Beginner,4.54,https://www.udemy.com/course/java-programming-...,Java Programming for Beginners to Java Object ...,CLEAR YOUR JAVA INTERVIEWS: GET ALL the SKILLS...,UDEMY
12,The Complete Java Development Bootcamp,Rayan Slim,Beginner,4.7,https://www.udemy.com/course/the-complete-java...,Become an Experienced Java Developer with Just...,Acquire the Java skills needed to pursue Web D...,UDEMY
13,The Complete Java Certification Course,Imtiaz Ahmad,Beginner,4.5,https://www.udemy.com/course/master-practical-...,Become a confident industry ready core Java de...,Gain enough experience to pass a core Java Pro...,UDEMY

In [11]:
data.isnull().sum()

Course Name           0
University            0
Difficulty Level      0
Course Rating         0
Course URL            0
Course Description    0
Skills                0
Platform              0
dtype: int64

In [12]:
# data['Difficulty Level'].value_counts()

In [13]:
# data['Course Rating'].value_counts()

In [14]:
# data['University'].value_counts()

In [15]:
data['Course Name']

0     Write A Feature Length Screenplay For Film Or ...
1     Business Strategy: Business Model Canvas Analy...
2                         Silicon Thin Film Solar Cells
3                                  Finance for Managers
4          Retrieve Data using Single-Table SQL Queries
                            ...
9     The Data Science Course 2022: Complete Data Sc...
10    Java Programming Masterclass covering Java 11 ...
11              Java Programming for Complete Beginners
12               The Complete Java Development Bootcamp
13               The Complete Java Certification Course
Name: Course Name, Length: 3536, dtype: object

In [16]:
data = data[['Course Name','Difficulty Level','University','Course Description','Skills']]

In [17]:
data.head(6)

,Course Name,Difficulty Level,University,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Beginner,Michigan State University,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Beginner,Coursera Project Network,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,Advanced,�cole Polytechnique,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,Intermediate,IESE Business School,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Beginner,Coursera Project Network,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...
5,Building Test Automation Framework using Selen...,Beginner,Coursera Project Network,Selenium is one of the most widely used functi...,maintenance test case test automation scree...

In [18]:
data['Course Name'] = data['Course Name'].str.replace(' ',',')

data['Course Name'] = data['Course Name'].str.replace(',,',',')
data['Course Name'] = data['Course Name'].str.replace(':','')
# data['Course Name'] = data['Course Name'].str.lower()
data['Course Description'] = data['Course Description'].str.replace(' ',',')
data['Course Description'] = data['Course Description'].str.replace(',,',',')
data['Course Description'] = data['Course Description'].str.replace('_','')
data['Course Description'] = data['Course Description'].str.replace(':','')
data['Course Description'] = data['Course Description'].str.replace('(','')
data['Course Description'] = data['Course Description'].str.replace(')','')


#removing paranthesis from skills columns 
data['Skills'] = data['Skills'].str.replace('(','')
data['Skills'] = data['Skills'].str.replace(')','')


data.head(5)

C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Name'] = data['Course Name'].str.replace(' ',',')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Name'] = data['Course Name'].str.replace(',,',',')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Name'] = data['Course Name'].str.replace(':','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Description'] = data['Course Description'].str.replace(' ',',')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Description'] = data['Course Description'].str.replace(',,',',')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Description'] = data['Course Description'].str.replace('_','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Description'] = data['Course Description'].str.replace(':','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['Course Description'] = data['Course Description'].str.replace('(','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Description'] = data['Course Description'].str.replace('(','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['Course Description'] = data['Course Description'].str.replace(')','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Course Description'] = data['Course Description'].str.replace(')','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:15: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['Skills'] = data['Skills'].str.replace('(','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Skills'] = data['Skills'].str.replace('(','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:16: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['Skills'] = data['Skills'].str.replace(')','')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\3315590702.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Skills'] = data['Skills'].str.replace(')','')

,Course Name,Difficulty Level,University,Course Description,Skills
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",Beginner,Michigan State University,"Write,a,Full,Length,Feature,Film,Script,In,thi...",Drama Comedy peering screenwriting film D...
1,"Business,Strategy,Business,Model,Canvas,Analys...",Beginner,Coursera Project Network,"By,the,end,of,this,guided,project,you,will,be,...",Finance business plan persona user experienc...
2,"Silicon,Thin,Film,Solar,Cells",Advanced,�cole Polytechnique,"This,course,consists,of,a,general,presentation...",chemistry physics Solar Energy film lambda...
3,"Finance,for,Managers",Intermediate,IESE Business School,"When,it,comes,to,numbers,there,is,always,more,...",accounts receivable dupont analysis analysis...
4,"Retrieve,Data,using,Single-Table,SQL,Queries",Beginner,Coursera Project Network,"In,this,course,you�ll,learn,how,to,effectively...",Data Analysis select sql database management...

In [19]:
data['tags'] = data['Course Name'] + data['Difficulty Level'] + data['Course Description'] + data['Skills']
data.head(5)

C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\1465779165.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tags'] = data['Course Name'] + data['Difficulty Level'] + data['Course Description'] + data['Skills']

,Course Name,Difficulty Level,University,Course Description,Skills,tags
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...",Beginner,Michigan State University,"Write,a,Full,Length,Feature,Film,Script,In,thi...",Drama Comedy peering screenwriting film D...,"Write,A,Feature,Length,Screenplay,For,Film,Or,..."
1,"Business,Strategy,Business,Model,Canvas,Analys...",Beginner,Coursera Project Network,"By,the,end,of,this,guided,project,you,will,be,...",Finance business plan persona user experienc...,"Business,Strategy,Business,Model,Canvas,Analys..."
2,"Silicon,Thin,Film,Solar,Cells",Advanced,�cole Polytechnique,"This,course,consists,of,a,general,presentation...",chemistry physics Solar Energy film lambda...,"Silicon,Thin,Film,Solar,CellsAdvancedThis,cour..."
3,"Finance,for,Managers",Intermediate,IESE Business School,"When,it,comes,to,numbers,there,is,always,more,...",accounts receivable dupont analysis analysis...,"Finance,for,ManagersIntermediateWhen,it,comes,..."
4,"Retrieve,Data,using,Single-Table,SQL,Queries",Beginner,Coursera Project Network,"In,this,course,you�ll,learn,how,to,effectively...",Data Analysis select sql database management...,"Retrieve,Data,using,Single-Table,SQL,QueriesBe..."

In [20]:
data['tags'].iloc[1]

'Business,Strategy,Business,Model,Canvas,Analysis,with,MiroBeginnerBy,the,end,of,this,guided,project,you,will,be,fluent,in,identifying,and,creating,Business,Model,Canvas,solutions,based,on,previous,high-level,analyses,and,research,data.,This,will,enable,you,to,identify,and,map,the,elements,required,for,new,products,and,services.,Furthermore,it,is,essential,for,generating,positive,results,for,your,business,venture.,This,guided,project,is,designed,to,engage,and,harness,your,visionary,and,exploratory,abilities.,You,will,use,proven,models,in,strategy,and,product,development,with,the,Miro,platform,to,explore,and,analyse,your,business,propositions.,,We,will,practice,critically,examining,results,from,previous,analysis,and,research,results,in,deriving,the,values,for,each,of,the,business,model,sections.Finance  business plan  persona user experience  business model canvas  Planning  Business  project  Product Development  presentation  Strategy business business-strategy'

In [21]:
new_df = data[['Course Name','tags']]

new_df.head(5)

,Course Name,tags
0,"Write,A,Feature,Length,Screenplay,For,Film,Or,...","Write,A,Feature,Length,Screenplay,For,Film,Or,..."
1,"Business,Strategy,Business,Model,Canvas,Analys...","Business,Strategy,Business,Model,Canvas,Analys..."
2,"Silicon,Thin,Film,Solar,Cells","Silicon,Thin,Film,Solar,CellsAdvancedThis,cour..."
3,"Finance,for,Managers","Finance,for,ManagersIntermediateWhen,it,comes,..."
4,"Retrieve,Data,using,Single-Table,SQL,Queries","Retrieve,Data,using,Single-Table,SQL,QueriesBe..."

In [22]:
new_df['tags'] = data['tags'].str.replace(',',' ')
new_df['Course Name'] = data['Course Name'].str.replace(',',' ')
new_df.rename(columns = {'Course Name':'course_name'}, inplace = True)
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())
new_df.head(5)

C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\383437564.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = data['tags'].str.replace(',',' ')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\383437564.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Course Name'] = data['Course Name'].str.replace(',',' ')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\383437564.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns = {'Course Name':'course_name'}, inplace = True)
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\383437564.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

,course_name,tags
0,Write A Feature Length Screenplay For Film Or ...,write a feature length screenplay for film or ...
1,Business Strategy Business Model Canvas Analys...,business strategy business model canvas analys...
2,Silicon Thin Film Solar Cells,silicon thin film solar cellsadvancedthis cour...
3,Finance for Managers,finance for managersintermediatewhen it comes ...
4,Retrieve Data using Single-Table SQL Queries,retrieve data using single-table sql queriesbe...

In [23]:
new_df.shape

(3536, 2)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()

In [25]:
import nltk 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)


new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\1264303300.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [27]:
def recommend(course):
    course_index = new_df[new_df['course_name'] == course].index[0]
    distances = similarity[course_index]
    course_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:]
    res = [i[0] for i in course_list]
#     for i in course_list:
#         print(dup.iloc[i[0]])
    return dup.iloc[res]

In [28]:
print("Enter the type of course you want??")
i = input()
new_dummy = new_df[new_df['course_name'].str.contains(i,case=False)]
s = new_dummy.iloc[0].course_name
print(s)

Enter the type of course you want??
java
Learn to Teach Java  Boolean Expressions If Statements and Iteration

In [29]:
res = recommend(s)
res['Course Rating'] = pd.to_numeric(res['Course Rating'], errors='coerce')

# res['Course Rating'] = res['Course Rating'].astype(float)
res['No.'] = np.arange(len(res))
res =res.sort_values(by=['No.','Course Rating'],ascending=[True,False])
res.drop(['No.'],axis=1)

C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\2419299022.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res['Course Rating'] = pd.to_numeric(res['Course Rating'], errors='coerce')
C:\Users\bhanu\AppData\Local\Temp\ipykernel_6536\2419299022.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res['No.'] = np.arange(len(res))

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,Platform
455,Learn to Teach Java: ArrayLists and 2D Arrays,University of California San Diego,Advanced,5.0,https://www.coursera.org/learn/teach-java-arra...,Learn to program with ArrayLists and 2-D Array...,test case method (computer programming) appr...,Coursera
1372,Learn to Teach Java: Inheritance and Recursion,University of California San Diego,Advanced,4.5,https://www.coursera.org/learn/teach-java-inhe...,Learn to program with Inheritance and Recursio...,node.js Writing ordered pair teaching recu...,Coursera
771,Learn to Teach Java: Writing Classes and Arrays,University of California San Diego,Advanced,4.6,https://www.coursera.org/learn/teach-java-clas...,Learn to program using Class design and 1-D Ar...,approximation error arrays c dynamic memory ...,Coursera
1215,"Learn to Teach Java: Sequences, Primitive Typ...",University of California San Diego,Advanced,4.9,https://www.coursera.org/learn/teach-java-sequ...,"Get started with the basics of Java, and prepa...",teaching Computer Programming modulo operati...,Coursera
3250,Computer Science: Programming with a Purpose,Princeton University,Advanced,4.1,https://www.coursera.org/learn/cs-programming-...,The basis for education in the last millennium...,Java Programming openfabrics alliance virtua...,Coursera
...,...,...,...,...,...,...,...,...
2536,The World of the String Quartet,Curtis Institute of Music,Not Calibrated,4.7,https://www.coursera.org/learn/string-quartet,"Arnold Steinhardt, first violin of the interna...",Art History language Innovation anguish mu...,Coursera
2646,The Ancient Greeks,Wesleyan University,Beginner,4.7,https://www.coursera.org/learn/ancient-greeks,This is a survey of ancient Greek history from...,flourishing ancient greece greek mythology ...,Coursera
2849,Music's Big Bang: The Genesis of Rock 'n' Roll,University of Florida,Intermediate,4.7,https://www.coursera.org/learn/rock-and-roll-m...,Explores the factors � musical and cultural � ...,great man theory music jazz history of rock...,Coursera
3005,Writing a Personal Essay,Wesleyan University,Advanced,4.4,https://www.coursera.org/learn/personal-essay,This class is the chance to create your person...,chemistry film essay writing creative writi...,Coursera
3278,Diversity and inclusion in the workplace,ESSEC Business School,Beginner,4.6,https://www.coursera.org/learn/diversity-inclu...,Diversity is a fact. It is also paradoxical. W...,Human Resources cognitive bias experience b...,Coursera

In [30]:
u = res[res['Platform'] == 'UDEMY']
u[:6]

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills,Platform,No.
10,Java Programming Masterclass covering Java 11 ...,Tim Buchalka,Beginner,4.50,https://www.udemy.com/course/java-the-complete...,Learn Java In This Course And Become a Compute...,Obtain proficiency in Java 8 and Java 11.,UDEMY,8
11,Java Programming for Complete Beginners,in28Minutes Official,Beginner,4.54,https://www.udemy.com/course/java-programming-...,Java Programming for Beginners to Java Object ...,CLEAR YOUR JAVA INTERVIEWS: GET ALL the SKILLS...,UDEMY,16
13,The Complete Java Certification Course,Imtiaz Ahmad,Beginner,4.50,https://www.udemy.com/course/master-practical-...,Become a confident industry ready core Java de...,Gain enough experience to pass a core Java Pro...,UDEMY,66
12,The Complete Java Development Bootcamp,Rayan Slim,Beginner,4.70,https://www.udemy.com/course/the-complete-java...,Become an Experienced Java Developer with Just...,Acquire the Java skills needed to pursue Web D...,UDEMY,95
6,[2022] Machine Learning and Deep Learning Boot...,Holczer Balazs,Advanced,4.30,https://www.udemy.com/course/introduction-to-m...,"Machine Learning, Neural Networks, Computer Vi...",Solving classification problems (naive Bayes c...,UDEMY,532
9,The Data Science Course 2022: Complete Data Sc...,365 Careers,Beginner,4.60,https://www.udemy.com/course/the-data-science-...,"Complete Data Science Training: Mathematics, S...",Fill up your resume with in demand data scienc...,UDEMY,564

THe above table represents all the courses recommended

In [32]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

In [33]:
import pickle

pickle.dump(similarity,open('similarity.pkl','wb'))
pickle.dump(new_df.to_dict(),open('course_list.pkl','wb')) #contains the dataframe in dict 
pickle.dump(new_df,open('courses.pkl','wb'))
pickle.dump(dup,open('dup.pkl','wb'))

In [34]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.14.0-py2.py3-none-any.whl (9.2 MB)
     ---------------------------------------- 9.2/9.2 MB 2.3 MB/s eta 0:00:00
Collecting pympler>=0.9
  Using cached Pympler-1.0.1-py3-none-any.whl (164 kB)
Collecting tzlocal>=1.1
  Using cached tzlocal-4.2-py3-none-any.whl (19 kB)
Requirement already satisfied: importlib-metadata>=1.4 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (4.11.3)
Requirement already satisfied: numpy in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (1.21.5)
Collecting altair>=3.2.0
  Using cached altair-4.2.0-py3-none-any.whl (812 kB)
Collecting rich>=10.11.0
  Using cached rich-12.6.0-py3-none-any.whl (237 kB)
Collecting protobuf<4,>=3.12
  Downloading protobuf-3.20.3-cp39-cp39-win_amd64.whl (904 kB)
     -------------------------------------- 904.2/904.2 kB 7.2 MB/s eta 0:00:00
Collecting pyarrow>=4.0
  Using cached pyarrow-10.0.0-cp39-cp39-win_amd64.whl (20.0 MB)
Requirement already satisfied: requests>=2.4 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (2.28.1)
Requirement already satisfied: click>=7.0 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (8.0.4)
Collecting semver
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: pandas>=0.21.0 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (1.4.4)
Requirement already satisfied: watchdog in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (2.1.6)
Requirement already satisfied: packaging>=14.1 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (21.3)
Collecting validators>=0.2
  Using cached validators-0.20.0-py3-none-any.whl
Collecting pydeck>=0.1.dev5
  Using cached pydeck-0.8.0-py2.py3-none-any.whl (4.7 MB)
Requirement already satisfied: toml in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions>=3.10.0.0 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (4.3.0)
Collecting cachetools>=4.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: tornado>=5.0 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (6.1)
Requirement already satisfied: python-dateutil in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (2.8.2)
Collecting blinker>=1.0.0
  Using cached blinker-1.5-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: pillow>=6.2.0 in c:\users\bhanu\anaconda3\lib\site-packages (from streamlit) (9.2.0)
Collecting gitpython!=3.1.19
  Using cached GitPython-3.1.29-py3-none-any.whl (182 kB)
Requirement already satisfied: jinja2 in c:\users\bhanu\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (2.11.3)
Requirement already satisfied: entrypoints in c:\users\bhanu\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (0.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\bhanu\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (4.16.0)
Requirement already satisfied: toolz in c:\users\bhanu\anaconda3\lib\site-packages (from altair>=3.2.0->streamlit) (0.11.2)
Requirement already satisfied: colorama in c:\users\bhanu\anaconda3\lib\site-packages (from click>=7.0->streamlit) (0.4.5)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.9-py3-none-any.whl (63 kB)
Requirement already satisfied: zipp>=0.5 in c:\users\bhanu\anaconda3\lib\site-packages (from importlib-metadata>=1.4->streamlit) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\bhanu\anaconda3\lib\site-packages (from packaging>=14.1->streamlit) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in c:\users\bhanu\anaconda3\lib\site-packages (from pandas>=0.21.0->streamlit) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\bhanu\anaconda3\lib\site-packages (from python-dateutil->streamlit) (1.16.0)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\bhanu\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bhanu\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bhanu\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (2022.9.14)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\bhanu\anaconda3\lib\site-packages (from requests>=2.4->streamlit) (1.26.11)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\bhanu\anaconda3\lib\site-packages (from rich>=10.11.0->streamlit) (2.11.2)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting tzdata
  Using cached tzdata-2022.6-py2.py3-none-any.whl (338 kB)
Collecting pytz-deprecation-shim
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: decorator>=3.4.0 in c:\users\bhanu\anaconda3\lib\site-packages (from validators>=0.2->streamlit) (5.1.1)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\bhanu\anaconda3\lib\site-packages (from jinja2->altair>=3.2.0->streamlit) (2.0.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\bhanu\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\bhanu\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit) (21.4.0)
Installing collected packages: commonmark, validators, tzdata, smmap, semver, rich, pympler, pyarrow, protobuf, cachetools, blinker, pytz-deprecation-shim, pydeck, gitdb, tzlocal, gitpython, altair, streamlit
Successfully installed altair-4.2.0 blinker-1.5 cachetools-5.2.0 commonmark-0.9.1 gitdb-4.0.9 gitpython-3.1.29 protobuf-3.20.3 pyarrow-10.0.0 pydeck-0.8.0 pympler-1.0.1 pytz-deprecation-shim-0.1.0.post0 rich-12.6.0 semver-2.13.0 smmap-5.0.0 streamlit-1.14.0 tzdata-2022.6 tzlocal-4.2 validators-0.20.0